"""Initial migration

Revision ID: 4ca09f1cb014
Revises: 
Create Date: 2026-09-21 12:42:47.134486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca09f1cb014'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('client_uid', sa.String(length=36), nullable=False),
    sa.Column('character_config', sa.String(length=255), nullable=True),
    sa.Column('history_uid', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('total_audio_duration', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_client_uid', 'sessions', ['client_uid'], unique=False)
    op.create_table('troll_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('troll_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('verdict', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_troll_records_created_at', 'troll_records', ['created_at'], unique=False)
    op.create_index('ix_troll_records_username', 'troll_records', ['username'], unique=False)
    op.create_table('viewers',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('streams_attended', sa.Integer(), nullable=True),
    sa.Column('total_tips', sa.Float(), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('last_seen', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('audio_generations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('voice', sa.String(length=100), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audio_generations_created_at', 'audio_generations', ['created_at'], unique=False)
    op.create_index('ix_audio_generations_session_id', 'audio_generations', ['session_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['viewers.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_timestamp', 'chat_messages', ['timestamp'], unique=False)
    op.create_index('ix_chat_messages_username', 'chat_messages', ['username'], unique=False)
    op.create_table('inside_jokes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('joke_name', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['username'], ['viewers.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inside_jokes_username', 'inside_jokes', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_inside_jokes_username', table_name='inside_jokes')
    op.drop_table('inside_jokes')
    op.drop_index('ix_chat_messages_username', table_name='chat_messages')
    op.drop_index('ix_chat_messages_timestamp', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_audio_generations_session_id', table_name='audio_generations')
    op.drop_index('ix_audio_generations_created_at', table_name='audio_generations')
    op.drop_table('audio_generations')
    op.drop_table('viewers')
    op.drop_index('ix_troll_records_username', table_name='troll_records')
    op.drop_index('ix_troll_records_created_at', table_name='troll_records')
    op.drop_table('troll_records')
    op.drop_index('ix_sessions_client_uid', table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###